server:
  port: 5250
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6603/schoolin
    username: root
    password: changeme

# jwt secret
shuaicj.security.jwt.secret: otherpeopledontknowit